### ISSUE TITLE
"Horizontal Line" component

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#103]
I've put this one in the Component document. In Xcode this is implemented as a simple NSBox:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/103326/74189032-faad2500-4c4f-11ea-9aba-479743165f45.png">

**Comment by netonjm** [comment]
Love it!

**Comment by netonjm** [comment]
This is allready handled by FigmaLineConverter https://github.com/netonjm/FigmaSharp/blob/master/FigmaSharp/FigmaSharp.Cocoa/Converters/FigmaLineConverter.cs#L42-L62

and we check this 

https://github.com/netonjm/FigmaSharp/blob/e3988a60d0d7c04a29f8c065175421cb71563af7/FigmaSharp/FigmaSharp/Converters/FigmaLineConverterBase.cs#L39

**Comment by hbons** [comment]
tracked in #209.
