### ISSUE TITLE
Implement simple Cocoa constraints

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#108]
For now we just need to implement the basic functionality that Figma supports, no autolayout.
- [x] Constraints relative to parent view: left|top|right|bottom|center-x|center-y.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/103326/74525740-26ffc480-4f22-11ea-850d-94aa1142c60e.png">

**Comment by netonjm** [comment]
AFAIK, autolayout is a StackView control in View world , no?

**Comment by hbons** [comment]
basically yes. I wonder if we can add a keyword for this like !stack. Since Figma doesn't have such a container.

**Comment by netonjm** [comment]
we'll need a special converter for this, it's enough handle it here

**Comment by hbons** [comment]
https://developer.apple.com/documentation/appkit/nsview/autoresizingmask

**Comment by netonjm** [comment]
gogo!

**Comment by hbons** [comment]
PR ready: #113
