### ISSUE TITLE
Simplify internal API for implementing new toolkits

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#110]
Looking at the internal design, it seems quite hard to implement new toolkits:
- Logic needs to be added to at least 3 different projects to implement a component
- There are many static/extension methods which make it hard to get a mental model of the API
- There's a lot of boilerplate classes

Goal should be to implement new toolkits by adding one new converter overriding one or two methods for every one control/object to convert in only one new project.

See also #105.

**Comment by hbons** [comment]
I had to change some stuff around and we basically have abstraction classes that do nothing but pass values around. See for example: https://github.com/netonjm/FigmaSharp/blob/master/FigmaSharp.Views/FigmaSharp.Views.Cocoa/ViewWrappers/Window.cs

This makes implementing new toolkits a tedious task. Also the interface design assumes Cocoa, so it won't work for other toolkits.
I think we should look into simplifying or get rid of these.

**Comment by netonjm** [comment]
I understand your point of view, but all this abstraction is necessary to share most code as possible between platforms, especially in our FigmaSharp Core which contains the transformation services.

This strategy to share code, has been a success in numerous tasks of transformation from GTK to native code in VS4Mac as is the case of the PropertyPanel, Toolbox, splitters.. we achieved excellent results with the minimum effort in the change.

> This makes implementing new toolkits a tedious task. Also the interface design assumes Cocoa, so it won't work for other toolkits.

No, every toolkit has it's own specific library and implements it's own platform, and native views, and converters.
In fact there are already implementations for all platforms made (and they work), but they are removed from the solution, as they are not maintained.

**Comment by hbons** [comment]
but here is the Cocoa window logic in the FigmaSharp.View library:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/103326/78252879-cfc6ab00-74f3-11ea-8245-61eefdab8c65.png">

Can we investigate a way to have a more simple abstraction in this library? For example, we need a container (like Window, Sheet, View etc.) and any interactable control (button, checkbox, etc.). Logic on top of that should be up to the toolkit developers.

**Comment by netonjm** [comment]
We can remove members from the interface, of course!

**Comment by hbons** [comment]
Yes! I guess what I'm trying to say is: I understand we need the wrappers,  I think we should reduce the number of them and reduce the number of properties that need to be implemented. :)

**Comment by netonjm** [comment]
Misunderstood the question then, go ahead! This was done in the early days, and probably some of this members are not used. They were created more oriented to be able to work directly with the  abstraction library in shared libraries.

**Comment by hbons** [comment]
I think this can be closed. For now, we can do it like these new Cocoa converters branch:
- base control converter class with the helper methods (instead of extension methods)
- Use only View() abstraction for now
