### ISSUE TITLE
Unify view/code converters

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#112]
Right now there are two implementations of converters (and all their helper extensions): one for views, and one for code. They are mostly identical in terms of the parsing logic, but need to be maintained separately which is prone to bugs or difference in behaviour.

We should research how we can unify these to avoid bugs and simplify converter implementation. Maybe through serializing the view objects to code or some other means.

**Comment by hbons** [comment]
Maybe it's easier the other way round: always start with code and just run that.

**Comment by netonjm** [comment]
This is important, but to do this I would like to firstly get something fully working in both scenarios, and then the refactoring.

**Comment by hbons** [comment]
sure 👍

**Comment by hbons** [comment]
I think we decided to keep things as is for now. Converters are also a bit more maintainable now with the new-controls branch.
