### ISSUE TITLE
NSSecureTextField

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#115]
<img width="130" alt="image" src="https://user-images.githubusercontent.com/103326/74603782-5f84d700-50b7-11ea-989b-a7ff21f608cf.png">

**Comment by hbons** [comment]
@vancura ideas for this? hidden text layer like `placeholder`?

**Comment by netonjm** [comment]
we can reuse the TextField converter here

**Comment by hbons** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/103326/79254442-0651dd80-7e85-11ea-860b-da73e074ea5f.png">

This would be nice.

**Comment by netonjm** [comment]
sounds perfect!

**Comment by hbons** [comment]
tracked in #209.
