### ISSUE TITLE
Automatically determine variable name types

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#122]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/103326/75038936-d35c2080-54b7-11ea-85d6-07b16cb2aaf2.png">

Right now we need to specify long names in the layers to generate useful and descriptive variable names. We should derive the type from the component:

```
🔹 Button/Standard
⬦ "save"
```

generates variable name: `saveButton`.

Alternatively we could write up a fixed list of strings for each component.

**Comment by netonjm** [comment]
we already do this
