### ISSUE TITLE
Use NSMatrix to group radio buttons

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#129]
See https://stackoverflow.com/questions/1456936/creating-a-cocoa-radio-button-programmatically

Radio buttons that are in the same group/frame should be in the same NSMatrix.

**Comment by hbons** [comment]
so references will be `myRadioGroup.myRadio.State`.

**Comment by netonjm** [comment]
No, the NSMatrix is obsolete, now cocoa groups the radio buttons if they are in the same layer and they have **the same handling in Activate**

**Comment by hbons** [comment]
ok, ignore! :)
