### ISSUE TITLE
Live preview slightly off y-position

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#157]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/103326/76437471-e88ee580-63b9-11ea-80e7-143ae7dbf1e9.png">

**Comment by netonjm** [comment]
2 issues here:
- Image when added to the ImageView is not aligning as expected
- and the buttons at bottom are layers from the new inherance mechanism which is not implemented

**Comment by hbons** [comment]
for 1: this also happens for windows without an image it seems.

**Comment by netonjm** [comment]
mm it seems we are taking wrong window size

**Comment by hbons** [comment]
The buttons at the bottom work fine, so this makes me think this is constraint related. Here the buttons and the last horizontal separator have BOTTOM constraints applied: 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/103326/78188669-ebd53880-7470-11ea-9880-ce44e8b06f7d.png">
