### ISSUE TITLE
Some constraints are not correctly aligned in first level

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#160]
NSView should react the same to constraints like any other view.

Example of 2 buttons in a group/frame with constraints that are not applied to the NSView:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/103326/76447367-dc5e5480-63c8-11ea-9834-eff3b5f12b6f.png">

**Comment by netonjm** [comment]
This issue is related to the layer inheriting, we don't handle this yet.

**Comment by netonjm** [comment]
this is a bug, every view has constraints, probably first level constraints issue

**Comment by netonjm** [comment]
related https://github.com/netonjm/FigmaSharp/issues/157
