### ISSUE TITLE
Idea: Password masking in both FigmaSharpApp and the extension is not needed

### ISSUE THREAD

**Issue by vancura** [netonjm/FigmaSharp#186]
It's just an idea, but I think masking here doesn't help. In fact, it makes it impossible to guess what the token is used here.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4982/79123269-0fb24b80-7d9a-11ea-9242-5c6191517f54.png">

Nobody will ever steal the token, on the end I don't think it's encrypted in the settings, so why mask it? :)

(Applies both to the app and the extension)

**Comment by hbons** [comment]
It's not a very high risk, but I do think it's needed. Figma only shows you the key once. Also think of video calls where you may screen share it accidentally.

The app one is stored in Keychain so it's encrypted. VS Mac has some ways to store it encrypted as well but I haven't looked into it yet.
