### ISSUE TITLE
fall back gracefully when FS extension not installed

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#193]
Not all developers will have the FS extension installed at first, and the solution still needs to be workable. Here's some things we can improve in case the extension is not installed:

- [ ] Use document name for folder instead of the ID
- [ ] Use plain folder icon

**Comment by netonjm** [comment]
It's not a good idea use document name as a directory name. I prefer leave the document id which is unique.
And related to plain folder icon, if the extension is not loaded it will use the standard vs4mac directory icon.
