### ISSUE TITLE
Translate "-" to "_" for image variable names

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#202]
`!image "update-installing"` should become `NSImageView update_installing` or `NSImageView updateInstalling`.

**Comment by hbons** [comment]
looks like this already partially happens:
```
// View:     updateinstalling
// NodeName: !image "update-installing"
// NodeType: FRAME
// NodeId:   33:154
updateinstalling = new AppKit.NSImageView();
updateinstalling.WantsLayer = true;
updateinstalling.Image = AppKit.NSImage.ImageNamed ("update-installing");;
```

but it's not changed at the declaration: 
```
private AppKit.NSImageView update-installing;
```

**Comment by netonjm** [comment]
I prefer a small redesign in how we generate this for something more robust, this adds more complexity, also it can fail in many scenarios.
