### ISSUE TITLE
The link to the Figma component library doesn't work

### ISSUE THREAD

**Issue by andreinitescu** [netonjm/FigmaSharp#212]
The table in the Wiki shows components for two platforms, for Cocoa and WPF. For WPF there's no link, but for Cocoa it points to the following URL which is not available:
https://www.figma.com/file/QzEgq2772k2eeMF2sVNc3kEY/macOS-Components

Per my understanding I must have and use these special components otherwise the FigmaSharpApp won't work (I tried with a a simple rectangle and it crashed)

**Comment by hbons** [comment]
hey @andreinitescu! we're currently working on getting this document public, I can't really say when this will happen. the WPF library doesn't exist yet. 

we have a lookup table to determine which Figma component translates into what control:
https://github.com/netonjm/FigmaSharp/blob/8810dca0152b08b27dfd12872914bce7c7780961/FigmaSharp.NativeControls/FigmaSharp.NativeControls/FigmaControlsExtensions.cs#L156

it's based on names, so as long as you name the components according to this list, the right converter will be called.

**Comment by hbons** [comment]
same as #179.
