### ISSUE TITLE
Implement a !placeholder feature on conversion

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#219]
this describes the use case better, at the expense of being a bit longer I think it's worth it.

We should process the current layer as a normal container NSView

**Comment by netonjm** [comment]
In what cases we need this? why not just use a normal Frame which is renderer as NSView by default?

**Comment by hbons** [comment]
Often when I want to use a !placeholder group there could be content inside, like a screenshot or just more layers that FigmaSharp isn't able to convert. So an empty group doesn't cover all the cases.

Here's what I expect:

```
- !placeholder "myPlaceholder"
    - a lot
    - of 
    - content
```
the content is ignored and generates an empty view, but with the right geometery and constraints:
```
NSView myPlaceHolder = new NSView();
myPlaceholder.Frame = ...;
myPlaceholder.Constraints = ...;
```
makes sense? :)

**Comment by netonjm** [comment]
yeah basically don't iterate in children when processing

**Comment by hbons** [comment]
I forgot to add: This is only for code generations. In the previewer we still want to see the content.
