### ISSUE TITLE
Process from layers !img all the states and import to the project

### ISSUE THREAD

**Issue by netonjm** [netonjm/FigmaSharp#225]
- [x] Define a layer spec to define images for different Themes and screensize
- [x] Implement the spec and generate all the resources in the project

It seems right know we generate in the generated code 2 NSImageViews (1 hidden)

test
https://www.figma.com/file/epVv8PrdSb66L6VtspbEGU/Untitled?node-id=0%3A1

**Comment by hbons** [comment]
👍

**Comment by hbons** [comment]
I'm thinking:
```
"myLayer" !theme:”Light”
"myLayer" !theme:”LightHC”
"myLayer" !theme:”Dark”
"myLayer" !theme:”DarkHC”
```
The theme names would be defined by the toolkit.
How should we handle this in code? Just hide/unhide the right views?

**Comment by hbons** [comment]
The !theme keyword should be usable for any layer, not just images. This is great for example for when we need to use custom colours that are not in the styles palette.

**Comment by netonjm** [comment]
![image](https://user-images.githubusercontent.com/1587480/82676797-3ee49400-9c47-11ea-8479-965d42da52a6.png)

@hbons what do you think about this?

**Comment by netonjm** [comment]
![image](https://user-images.githubusercontent.com/1587480/82676922-76534080-9c47-11ea-9c36-d5fc874d978d.png)

I think this is an interesting approach:
this could generate something like:

Resources:
about-hero.png
about-hero2@.png
...

and code:
var AboutHero = new ImageView () { Src="about-hero.png" }

**Comment by netonjm** [comment]
After a conversation the final approach:

![image](https://user-images.githubusercontent.com/1587480/82680138-23c85300-9c4c-11ea-8354-c496d73d310c.png)

**Comment by netonjm** [comment]
Reopening because implemented the wrong image
