### ISSUE TITLE
!content rendered in app needs to be offset by titlebar height

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#228]

**Comment by netonjm** [comment]
a screenshot or screencast could be very useful here 👍

**Comment by hbons** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/103326/82693551-0aca9c80-9c62-11ea-9a25-be4196475ea0.png">

old bug seems back. (or i did something wrong with the !content container)

**Comment by hbons** [comment]
This is working fine now. I think it was a bug but also some windows were using a wrong frame for !content. :)

**Comment by netonjm** [comment]
oops! nice is now fixed! :)
