### ISSUE TITLE
Support AutoLayout -> NSStackView

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#251]
We need some way to define stacks for content that's flexible.

For example, we need these buttons to grow horizontally in the right way when translated.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/103326/83690175-8fb59e80-a5f0-11ea-9d7f-84bff61524d3.png">

We should convert Figma's AutoLayout objects to NSStackView.

Features:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/103326/83742094-48afc380-a659-11ea-95e3-dd3075885ac2.png">

- [x] Horizontal/Vertical orientation
- [x] Left/Right padding
- [x] Top/Bottom padding
- [x] Spacing

There's also flexible/fixed height, but I'm not sure we need that.

**Comment by netonjm** [comment]
why we need a "stack" tag here? maybe detect autolayout here should be enought?

**Comment by hbons** [comment]
AutoLayout does not support constraints. :( So in this example the footer area with the buttons stays fixed when the window is resized.

**Comment by hbons** [comment]
On DM Jose told me we don't actually need these constraints. We can achieve the same effect with multiple stacks. Just had to change my way of thinking about it. :)

**Comment by hbons** [comment]
We "just" need the code generation part now. @netonjm you're much better than me here, do you want to take a look? :)
