### ISSUE TITLE
Recreate documents with new controls

### ISSUE THREAD

**Issue by netonjm** [netonjm/FigmaSharp#254]
- [x] ea4pU30ht61lUJXcr0TFIF
- [x] iGRStx9nXABd4C0mxZXTsn
- [x] 7E9P9fEYGJijRXigfSz0kP

**Comment by netonjm** [comment]
@hbons  any update on this?

**Comment by hbons** [comment]
I will do this after I implement !theme support.

**Comment by hbons** [comment]
Done.
