### ISSUE TITLE
Discord link in readme isn't an invite.

### ISSUE THREAD

**Issue by MatFillion** [netonjm/FigmaSharp#282]
Hi! 👋 

I was curious about this project and wanted to learn more so I clicked the discord link in the README.md but I realised it isn't an invite, it's unusable for people like me who are not part of the server already.
I am referring to this link https://discord.com/channels/710495994667728996/710495994667728999

You should be able to create an invite link to your channel if you have the required permissions. It should be something like https://discord.gg/asDQE4f   (random digits for the last part). Do not forget to set the link to never expire when you create it.

**Comment by netonjm** [comment]
Thank you very much for your interest in the project, and thank you for informing us of the wrong link!
I just fixed it, here you have it in case you need it https://discord.com/invite/F3GEYqp

Of course ask what you need and if you want to contribute you are welcome!
