### ISSUE TITLE
Question: where does this fit in?

### ISSUE THREAD

**Issue by mzhukovs** [netonjm/FigmaSharp#3]
I'm having a bit of trouble understanding what the use case for this library is, so apologies in advance for the basic question. I do not currently use Figma but was looking at it as a potential option for mocking up some views before development.... so my question is how would this library fit into the overall workflow of going from design to development? (just at a high level)

**Comment by netonjm** [comment]
Hello @mzhukovs, 

Thank you for your interest in the project.

Right now, the use case is limited to render your figma designed views into an application. 
To accomplish this, the library has a conversion system from Figma objects to native specific platform views. Once the library finish the conversion, you can search recursively for the desired converted view (Keep reading, I'll explain later), change properties or handle events to it , and include in your favorite app.

Let's put a practical case, for example, suppose we want use it in a WinForms application. 

We open the Figma editor and created a new File, drop a Frame and inside it a grey Rectangle with a label.

The Url of this page, contains the ID of your Figma File. With this ID the library requests to the Figma API all the objects and layers that we created, and it will end into a parsing process that will generate:

- **From the Frame:**   TransparentControl (it’s a custom view based on System.Windows.Forms.Control)

- **From the Rectangle:** TransparentControl (custom view based on System.Windows.Forms.Control)

- **From the Label:** TransparentLabelControl (custom view based on System.Windows.Forms.Control)

These generated views preserve the same parent / child hierarchy, and the values entered in the editor respecting the sizes, background color, border, font ... etc ..

Right now, the system is not very flexible, and it’s injected as it is generated in our application in a view that we want base (but all this will change with the next update).

The library also includes a tool that allows you to export your remote file figma with all the images included into a real files for local usage.

What are the plans for the future?

Not sure! But it could be something like:

- Introduction of new platforms / UI toolkits
     - Xamarin.Forms
     - Wpf
     - Xamarin.iOS
     - Xamarin.Android
     - WinForms
     -?
- Improvements and adjustments when parsing native views
- Create Application Controls from Figma designer (textboxes, comboboxes, grids ...)
- User Custom Controls
- Figma to Code/Snippets generate the code to copy in our app

**Comment by mzhukovs** [comment]
Thanks for the detailed write-up, not sure if it's useful yet as I am still exploring options but will definitely circle back to this to check it out in more detail if I go with Figma.
