### ISSUE TITLE
Implement macOS components

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#32]
https://github.com/netonjm/FigmaSharp/wiki/Behaviour,-Keywords-and-Syntax

Special behaviours:

high priority:
- [x] Radios and checkboxes: respect checked state
- [x] Radios: Make radio components in the same parent group part of the same group in code
- [x] Buttons: respect Default (blue) button state
- [x] Window: respect window size and scrollbars
- [x] Textfield: respect Placeholder text

low priority:
- [x] Use mini controls for the "Small" components

**Comment by netonjm** [comment]
what means? Window: respect window size and scrollbars

**Comment by netonjm** [comment]
@hbons ^^

**Comment by hbons** [comment]
Fixed.
