### ISSUE TITLE
Simplify getting started API

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#50]
Should be able to create a native view from Figma document with a one liner (or two at most).

**Comment by netonjm** [comment]
this could be moved after finish the bundler

**Comment by hbons** [comment]
yea, low priority.

**Comment by hbons** [comment]
@netonjm I remember you've improved this a while back. 👍 also this is now less important as our new focus for users is more the Figma API and the tooling and not the things inbetween. :)
