### ISSUE TITLE
Fix geometry for Cocoa components

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#57]
Sometimes this is still wrong.

**Comment by netonjm** [comment]
Not sure if you mean the calculated Frame of the rendered view

**Comment by hbons** [comment]
Yep, that's what I mean. :) They're still cut off like in the Bundler example.

**Comment by netonjm** [comment]
We have a semi-fix! :-)

**Comment by hbons** [comment]
This has been fixed!
