### ISSUE TITLE
New bundling model

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#97]
- [x] Remove ".FigmaPackages" and use default namespace

@netonjm 
- [x] Find the correct namespace to use automatically
- [x] Figma documents should become References, create a toplevel "Figma" folder in project
<img width="281" alt="image" src="https://user-images.githubusercontent.com/103326/75082723-5364a380-5515-11ea-86a5-f3c23a033a17.png">

- [x] Figma reference context menu:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/103326/75082765-89098c80-5515-11ea-874b-23d1f3c09242.png">

- [x] <s>Create "Bundle Figma Document Here" command to allow generating code at any location in the project:</s>

- [x] Keep track of generated code's "parent" Figma document through csproj metadata

- [ ] Menu structure:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/103326/75045946-7e72d700-54c4-11ea-86fc-d3b0fdc25822.png">

@hbons Update the bundler tool design
- [x] Design new UI for bundler tool
- [x] Design update mode:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/103326/75082814-bc4c1b80-5515-11ea-8923-3ed1609ecb49.png">

- [x] "Namespace:" field to set manually, also set it in the manifest
- [x] Add way to select a Figma reference to generate from

**Comment by netonjm** [comment]
great! thanks!

**Comment by hbons** [comment]
also see #98.

**Comment by hbons** [comment]
Instead of references, we should do movable Package folders for now. This already works, except for the icon and name. So we just need that cosmetic fix.

**Comment by hbons** [comment]
What do you think about dropping the "FigmaPackages" namespace? We should default to the selected namespace and let the user decide if they want to add extra namespaces.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/103326/79229828-eeb62d00-7e63-11ea-9fdd-090d976b0c37.png">

**Comment by netonjm** [comment]
Sounds good to me!
